@extends('layout.master')
@section('content')
    <table class="table table-bordered">
        <tr>
            <th>abc</th>
            <th>abc</th>
            <th>abc</th>
            <th>abc</th>
            <th>abc</th>
        </tr>
        <tr>
            <td>abc</td>
            <td>abc</td>
            <td>abc</td>
            <td>abc</td>
            <td>abc</td>
        </tr>
    </table>
@endsection